= Basic Concepts

Starling might be a compact framework, but it still boasts a significant number of packages and classes.
It is built around several basic concepts that are designed to complement and extend each other.
Together, they provide you with a set of tools that empower you to create any application you can imagine.

Display Programming:: Every object that is rendered on the screen is a _display object_, organized in the _display list_.
Textures & Images:: To bring pixels, forms and colors to the screen, you will learn to use the _Texture_ and _Image_ classes.
Dynamic Text:: Rendering of dynamic text is a basic task in almost every application.
Event Handling:: Communication is key! Your display objects need to talk to each other, and they can do that via Starling's powerful event system.
Animation:: Bring some motion into the picture! There are different strategies to animate your display objects.
Asset Management:: Learn how to load and organize all kinds of assets, like textures and sounds.
Special Effects:: Effects and filters that will make your graphics stand out.
Utilities:: A number of helpers to make your life easier.

We've got a lot of ground to cover, so, in the words of Super Mario: "Let's-a go!"
